export const data = [
    {
        title: "The dark Knight",
        category: "Action",
        id: Math.random(),
        rate: 10,
        cover: "https://m.media-amazon.com/images/I/71R98O5lYuL._AC_SY679_.jpg",
        cast: "Cristian Bale, Heath Ledger, Micheal Cane",
        release: "2008-07-18",
    },
    {
        title: "Gone Girl",
        category: "Mistery",
        id: Math.random(),
        rate: 7,
        cover: "https://i.pinimg.com/originals/18/fb/0b/18fb0b7974cebce7b87bd084962f1de5.jpg",
        cast: "Ben Affleck, Rosmarie Pike, Neil Harris",
        release: "2014-10-03 ",
    },
    {
        title: "Lock stock and two smoking barrels",
        category: "Crime",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
        cast: "Nick Moran ,Jason Statham ,Dexter Fletcher",
        release: "1998-08-28",
    },
    {
        title: "The Departed",
        category: "Crime, Mystery",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/I/510gCMld+uL._AC_.jpg",
        cast: "Jack Nickelson, Matt Damon, Dicapprio",
        release: "2006-08-20",
    },
    {
        title: "V for Vendetta",
        category: "Action",
        id: Math.random(),
        rate: 9,
        cover: "https://miro.medium.com/max/1189/1*Etx-JkqJ5fGz9DnwLVlzNA.jpeg",
        cast: "Natalie Portman, Hugo Weaving",
        release: "2006-03-16",
    },
    {
        title: "Pulp Fiction",
        category: "Drama",
        id: Math.random(),
        rate: 10,
        cover: "https://cdn.europosters.eu/image/750/posters/pulp-fiction-cover-i1288.jpg",
        cast: "John Travolta, Uma Thurman, Samuel L. Jackson",
        release: "1994-10-14",
    },
    {
        title: "Hustle",
        category: "Sport, Comedy",
        id: Math.random(),
        rate: 6,
        cover: "https://m.media-amazon.com/images/M/MV5BYjdhYTE3NjMtZjI3OC00NzVlLWFiNTUtNzQ3NDNiNTI3NDg4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        cast: "Adam Sandler, Queen Latifah",
        release: "2022-06-03",
    },
    {
        title: "The Room",
        category: "Drama apparently",
        id: Math.random(),
        rate: 2,
        cover: "https://m.media-amazon.com/images/M/MV5BYjEzN2FlYmYtNDkwMC00NGFkLWE5ODctYmE5NmYxNzE2MmRiXkEyXkFqcGdeQXVyMjMwODc5Mw@@._V1_.jpg",
        cast: "Tommy Wiseau, Juliette Danielle",
        release: "2003-06-27",
    },
];
